#!/bin/sh

# go path
export GOPATH="${HOME}/.go"

# update path
export PATH=/usr/local/bin:${PATH}:/sbin:/usr/local/sbin

# add go path
export PATH="/usr/local/go/bin:${GOPATH}/bin:${PATH}"

# add rust path
export PATH="${HOME}/.cargo/bin:${PATH}"

# add bcc tools path
export PATH="/usr/share/bcc/tools:${PATH}"

# add gnu getopt
export PATH="/usr/local/opt/gnu-getopt/bin:${PATH}"

# update cdpath
export CDPATH=${CDPATH}:${GOPATH}/src/github.com:${GOPATH}/src/golang.org:${GOPATH}/src
